server {
  listen 3000;
  server_name _;
  client_max_body_size 24m;
  resolver 127.0.0.11 valid=10s ipv6=off;
  set $koffy_billing_api http://koffy-billing-api:8080;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass $koffy_billing_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /auth/ {
    proxy_pass $koffy_billing_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
